/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	xapicomv1 "github.com/Tasdidur/xcrd/pkg/apis/xapi.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeXcrds implements XcrdInterface
type FakeXcrds struct {
	Fake *FakeXapiV1
	ns   string
}

var xcrdsResource = schema.GroupVersionResource{Group: "xapi.com", Version: "v1", Resource: "xcrds"}

var xcrdsKind = schema.GroupVersionKind{Group: "xapi.com", Version: "v1", Kind: "Xcrd"}

// Get takes name of the xcrd, and returns the corresponding xcrd object, and an error if there is any.
func (c *FakeXcrds) Get(ctx context.Context, name string, options v1.GetOptions) (result *xapicomv1.Xcrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(xcrdsResource, c.ns, name), &xapicomv1.Xcrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xapicomv1.Xcrd), err
}

// List takes label and field selectors, and returns the list of Xcrds that match those selectors.
func (c *FakeXcrds) List(ctx context.Context, opts v1.ListOptions) (result *xapicomv1.XcrdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(xcrdsResource, xcrdsKind, c.ns, opts), &xapicomv1.XcrdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &xapicomv1.XcrdList{ListMeta: obj.(*xapicomv1.XcrdList).ListMeta}
	for _, item := range obj.(*xapicomv1.XcrdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested xcrds.
func (c *FakeXcrds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(xcrdsResource, c.ns, opts))

}

// Create takes the representation of a xcrd and creates it.  Returns the server's representation of the xcrd, and an error, if there is any.
func (c *FakeXcrds) Create(ctx context.Context, xcrd *xapicomv1.Xcrd, opts v1.CreateOptions) (result *xapicomv1.Xcrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(xcrdsResource, c.ns, xcrd), &xapicomv1.Xcrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xapicomv1.Xcrd), err
}

// Update takes the representation of a xcrd and updates it. Returns the server's representation of the xcrd, and an error, if there is any.
func (c *FakeXcrds) Update(ctx context.Context, xcrd *xapicomv1.Xcrd, opts v1.UpdateOptions) (result *xapicomv1.Xcrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(xcrdsResource, c.ns, xcrd), &xapicomv1.Xcrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xapicomv1.Xcrd), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeXcrds) UpdateStatus(ctx context.Context, xcrd *xapicomv1.Xcrd, opts v1.UpdateOptions) (*xapicomv1.Xcrd, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(xcrdsResource, "status", c.ns, xcrd), &xapicomv1.Xcrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xapicomv1.Xcrd), err
}

// Delete takes name of the xcrd and deletes it. Returns an error if one occurs.
func (c *FakeXcrds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(xcrdsResource, c.ns, name), &xapicomv1.Xcrd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeXcrds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(xcrdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &xapicomv1.XcrdList{})
	return err
}

// Patch applies the patch and returns the patched xcrd.
func (c *FakeXcrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *xapicomv1.Xcrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(xcrdsResource, c.ns, name, pt, data, subresources...), &xapicomv1.Xcrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*xapicomv1.Xcrd), err
}
