/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	xapicomv1 "github.com/Tasdidur/xcrd/pkg/apis/xapi.com/v1"
	versioned "github.com/Tasdidur/xcrd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Tasdidur/xcrd/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/Tasdidur/xcrd/pkg/client/listers/xapi.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// XcrdInformer provides access to a shared informer and lister for
// Xcrds.
type XcrdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.XcrdLister
}

type xcrdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewXcrdInformer constructs a new informer for Xcrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewXcrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredXcrdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredXcrdInformer constructs a new informer for Xcrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredXcrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XapiV1().Xcrds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XapiV1().Xcrds(namespace).Watch(context.TODO(), options)
			},
		},
		&xapicomv1.Xcrd{},
		resyncPeriod,
		indexers,
	)
}

func (f *xcrdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredXcrdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *xcrdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&xapicomv1.Xcrd{}, f.defaultInformer)
}

func (f *xcrdInformer) Lister() v1.XcrdLister {
	return v1.NewXcrdLister(f.Informer().GetIndexer())
}
